export { Config, parseSnapshotConfig } from './config.js'
export { RepositorySnapshotStore } from './snapshot.js'
export { extractFallbackSymbols } from './fallback.js'
export { buildSymbolIndex, InternalSymbolIndexStore } from './symbol-index.js'
export { buildRepoMap, querySymbols } from './projections.js'
export { decodeProjectionCursor, encodeProjectionCursor } from './cursor.js'
export { ReadonlyLspAdapter } from './lsp-adapter.js'
export { createCodeIntelligenceTools, createContextTools } from './tools.js'
export { createSessionRuntimeResolver } from './session-runtime.js'
export type { SessionCodeIntelligenceRuntime, SessionRuntimeResolver } from './session-runtime.js'
export { createContextCompiler, CONTEXT_CAPABILITY_VERSION, CONTEXT_COMPILER_POLICY_VERSION } from './context-compiler.js'
export type { ContextCompilerHandle } from './context-compiler.js'
export { apply, inject, mountCodeIntelligence, name, provide } from './plugin.js'
export type { CodeIntelligenceConfig, CodeIntelligenceRuntimeOptions } from './plugin.js'
export type { RepoMapOptionsV1, SymbolQueryV1 } from './projections.js'
export type { SnapshotConfigV1, SourceMeasurementV1, RepositorySnapshotV1, RepoFileSummaryV1 } from './types.js'
export type { InternalSymbolRelationV1, SymbolAdapterResultV1, InternalSymbolEntryV1 } from './types.js'
export type { AdapterUnavailableCode, AdapterUnavailableV1, HostNetworkIsolation, LspDeploymentConfigV1, LspDeploymentEnvironmentKey } from './types.js'
export type { ContextCompiler, ContextCompilerOptions, ContextCompilerStats } from './types.js'
